spring:
  datasource:
    activiti:
       url: jdbc:mysql://localhost:3306/bpm?useUnicode=true&characterEncoding=utf8&useSSL=false
       username: root
       password: root
       driverClassName: com.mysql.jdbc.Driver
       type: com.alibaba.druid.pool.DruidDataSource
    