server:
  port: 9088

eureka:
  instance:
    hostname: eureka-master
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: true
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:123456@eureka-backup:9089/eureka/
security:
  user:
    name: admin
    password: 123456