server:
  port: 9031

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@eureka-backup:9089/eureka/
hystrix:  
  command:  
    default:  
      execution:  
        timeout:  
          enabled: false